# Data Processing

In [1]:
# Import libraries
import pandas as pd
import re

In [2]:
# Import data
data_raw = pd.read_csv('AviationData_cleaned_Make.csv', encoding = 'utf-8')
data_raw.head()

,Event Id,Investigation Type,Accident Number,Event Date,Location,Country,Latitude,Longitude,Airport Code,Airport Name,...,Purpose of Flight,Air Carrier,Total Fatal Injuries,Total Serious Injuries,Total Minor Injuries,Total Uninjured,Weather Condition,Broad Phase of Flight,Report Status,Publication Date
0,20191118X84400,Accident,GAA20CA081,11/17/2019,"West Jefferson, OH",United States,39.935555,-83.236389,49OH,NaN,...,Personal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Preliminary,11/19/2019
1,20191116X25814,Accident,GAA20CA076,11/15/2019,"San Antonio, TX",United States,NaN,NaN,SAT,San Antonio Intl,...,Personal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Preliminary,11/19/2019
2,20191112X03916,Accident,GAA20CA067,11/12/2019,"Pembroke Pines, FL",United States,26.001111,-80.240833,HWO,North Perry,...,Instructional,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Preliminary,11/14/2019
3,20191112X40210,Accident,GAA20CA080,11/11/2019,"Fitzgerald, GA",United States,31.683889,-83.270834,FZG,Fitzgerald Muni,...,Personal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Preliminary,11/20/2019
4,20191111X00550,Accident,GAA20CA070,11/11/2019,"Kalispell, MT",United States,41.240277,-120.526111,9CL3,Likely,...,Personal,NaN,NaN,NaN,NaN,2.0,NaN,NaN,Preliminary,11/20/2019

In [14]:
data_raw

,Event Id,Investigation Type,Accident Number,Event Date,Location,Country,Latitude,Longitude,Airport Code,Airport Name,...,Purpose of Flight,Air Carrier,Total Fatal Injuries,Total Serious Injuries,Total Minor Injuries,Total Uninjured,Weather Condition,Broad Phase of Flight,Report Status,Publication Date
0,20191118X84400,Accident,GAA20CA081,11/17/2019,"West Jefferson, OH",United States,39.935555,-83.236389,49OH,NaN,...,Personal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Preliminary,11/19/2019
1,20191116X25814,Accident,GAA20CA076,11/15/2019,"San Antonio, TX",United States,NaN,NaN,SAT,San Antonio Intl,...,Personal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Preliminary,11/19/2019
2,20191112X03916,Accident,GAA20CA067,11/12/2019,"Pembroke Pines, FL",United States,26.001111,-80.240833,HWO,North Perry,...,Instructional,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Preliminary,11/14/2019
3,20191112X40210,Accident,GAA20CA080,11/11/2019,"Fitzgerald, GA",United States,31.683889,-83.270834,FZG,Fitzgerald Muni,...,Personal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Preliminary,11/20/2019
4,20191111X00550,Accident,GAA20CA070,11/11/2019,"Kalispell, MT",United States,41.240277,-120.526111,9CL3,Likely,...,Personal,NaN,NaN,NaN,NaN,2.0,NaN,NaN,Preliminary,11/20/2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84084,20041105X01764,Accident,CHI79FA064,08/02/1979,"Canton, OH",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,1.0,2.0,NaN,NaN,VMC,APPROACH,Probable Cause,04/16/1980
84085,20001218X45448,Accident,LAX96LA321,06/19/1977,"EUREKA, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,IMC,CRUISE,Probable Cause,09/12/2000
84086,20061025X01555,Accident,NYC07LA005,08/30/1974,"Saltville, VA",United States,36.922223,-81.878056,NaN,NaN,...,Personal,NaN,3.0,NaN,NaN,NaN,IMC,CRUISE,Probable Cause,02/26/2007
84087,20001218X45447,Accident,LAX94LA336,07/19/1962,"BRIDGEPORT, CA",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,4.0,0.0,0.0,0.0,UNK,UNKNOWN,Probable Cause,09/19/1996
84088,20001218X45444,Accident,SEA87LA080,10/24/1948,"MOOSE CREEK, ID",United States,NaN,NaN,NaN,NaN,...,Personal,NaN,2.0,0.0,0.0,0.0,UNK,CRUISE,Probable Cause,NaN

In [3]:
# Select existing features
select_columns = ['Injury Severity', 'Event Date', 'Location', 'Investigation Type', 'Country','Amateur Built',
                  'Aircraft Category', 'Airport Code', 'Aircraft Damage', 'Make', 
                  'Broad Phase of Flight', 'Purpose of Flight', 'FAR Description', 'Weather Condition']

In [4]:
# Create data with the desired features and further clean the data
df_select = data_raw.loc[ : , select_columns]

# Data exploration
df_select.info()

# Frequency check for "Injury Severity" column
df_select['Injury Severity'].value_counts()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 84089 entries, 0 to 84088
Data columns (total 14 columns):
Injury Severity          84089 non-null object
Event Date               84089 non-null object
Location                 84013 non-null object
Investigation Type       84085 non-null object
Country                  83582 non-null object
Amateur Built            83497 non-null object
Aircraft Category        27338 non-null object
Airport Code             47649 non-null object
Aircraft Damage          81413 non-null object
Make                     84089 non-null object
Broad Phase of Flight    77398 non-null object
Purpose of Flight        79297 non-null object
FAR Description          27033 non-null object
Weather Condition        81028 non-null object
dtypes: object(14)
memory usage: 9.0+ MB

Non-Fatal      63410
Fatal          16940
Incident        3395
Unavailable      344
Name: Injury Severity, dtype: int64

In [5]:
# Drop columns where non-null values take up less than 20% of total records
df_select = df_select.dropna(thresh = df_select.shape[0]*0.2, how = 'all', axis = 1)
df_select = df_select.dropna(thresh = df_select.shape[1]*0.6, how = 'all', axis = 0)


# Remove 'unavailable' and 'blank' data from 'Injury Severity' column
df_select = df_select[df_select['Injury Severity'].notnull()][df_select['Injury Severity'] != 'Unavailable']

In [6]:
# Fill NA values in 'Aircraft Category' and 'Airport Code'
df_select['Aircraft Category'] = df_select['Aircraft Category'].fillna('Unknown')
df_select['Airport Code'] = df_select['Airport Code'].fillna('NonAirport')

In [7]:
# Feature engineering
df_select['Event Date'] = pd.to_datetime(df_select['Event Date'])
df_select['Year'] =  pd.DatetimeIndex(df_select['Event Date']).year
df_select['Month'] =  pd.DatetimeIndex(df_select['Event Date']).month
df_select['Weekday'] =  pd.DatetimeIndex(df_select['Event Date']).dayofweek

df_select['State'] = df_select['Location'].str.split(',').str[-1]

In [8]:
# Remove 'Location' and 'Event Date'
df_select = df_select.drop(['Event Date', 'Location'], axis=1)

In [9]:
# Print NA values counts for checking tnad then dorp rows with NA values
print('Check number of NA values from selected columns:\n', df_select.isnull().sum())

# Drop na
df_select.dropna(axis = 0, inplace = True)
df_select.reset_index(drop = True, inplace = True)

Check number of NA values from selected columns:
 Injury Severity              0
Investigation Type           1
Country                    499
Amateur Built              327
Aircraft Category            0
Airport Code                 0
Aircraft Damage           2352
Make                         0
Broad Phase of Flight     5941
Purpose of Flight         4098
FAR Description          56515
Weather Condition         2315
Year                         0
Month                        0
Weekday                      0
State                       57
dtype: int64

In [10]:
# Filter 'FAR Description' that contains 'Part'
df_select = df_select[df_select['FAR Description'].str.match('Part')]
df_select['FAR Description'] = df_select['FAR Description'].str.split(':').str[0]

# Replace / with _
df_select['Purpose of Flight'] = df_select['Purpose of Flight'].str.replace(r'/', '_', regex = False)

In [11]:
print("The final cleaned data has", df_select.shape[0], "rows, and has", df_select.shape[1], "columns.")

The final cleaned data has 20111 rows, and has 16 columns.

In [12]:
# Save the cleaned dataset to csv
#df_select.to_csv('AviationData_cleaned_final.csv', index = None, header = True)

In [13]:
df_select.to_csv('AviationData_cleaned_V3.csv', index = None, header = True)